[package]
name = "taipo"
version = "0.1.0"
authors = ["Rob Parrett <robparrett@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [
  "bevy/bevy_gltf",
  "bevy/bevy_winit",
  "bevy/render",
  "bevy/png",
]

[dependencies]
#bevy = { version = "0.4", default-features = false}
#bevy = { path = "../bevy-fork", default-features=false }
#bevy = { git = "https://github.com/bevyengine/bevy/", rev="7be096a254e86bd6388d96ea10b56b9ed6210685", default-features=false }
bevy = { git = "https://github.com/rparrett/bevy/", rev="bc4fe9b186db3f32eef38fc4241289df480fa949", default-features=false }

bevy_tiled_prototype = { git = "https://github.com/rparrett/bevy_tiled", rev="c9292e5aa9cc3252d27a6ad470e74a9937b19da3", default-features=false, features=["web"] }
#bevy_tiled_prototype = { path = "../bevy_tiled", default-features=false, features=["web"] }

bevy_asset_ron = { git = "https://github.com/jamadazi/bevy_asset_ron/", rev="a40e9b17af783e588cc94409e37324d87c2d17dd" }

#bevy_kira_audio = { git = "https://github.com/NiklasEi/bevy_kira_audio", rev="d71fd33700763c4feabd6b18d21563246192f37f", features=["ogg"] }
bevy_kira_audio = { git = "https://github.com/rparrett/bevy_kira_audio", rev="6b24410c6d1d694c6d6c1c2d312f0a956b74b24c", features=["wav"] }
#bevy_kira_audio = { path = "../bevy_kira_audio", features=["wav"] }

rand = { version = "0.8" }
getrandom = { version = "0.1", features = ["wasm-bindgen"] }
serde = {version = "1", features = ["derive"]}
nom = "6.0"
anyhow = "1.0"
ron = "0.6.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
#bevy_webgl2 = { version = "0.4.0" }
#bevy_webgl2 = { path = "../bevy_webgl2" }
bevy_webgl2 = { git = "https://github.com/mrk-its/bevy_webgl2", rev="b5e842e421be56af9e69ababdaeb028b05c5b7a2" }

[patch.crates-io]
#bevy = { git = "https://github.com/bevyengine/bevy/", rev="1ca8ce4a799af8dab2d926366de9ac3c8d30939c", default-features=false }
bevy = { git = "https://github.com/rparrett/bevy/", rev="bc4fe9b186db3f32eef38fc4241289df480fa949", default-features=false }
#bevy = { path = "../bevy-fork", default-features=false }

[patch.'https://github.com/bevyengine/bevy']
bevy = { git = "https://github.com/rparrett/bevy/", rev="bc4fe9b186db3f32eef38fc4241289df480fa949", default-features=false }
#bevy = { path = "../bevy-fork", default-features=false }
